### ISSUE TITLE
Metahub crash after "close pr" event

### ISSUE THREAD

**Issue by vojtajina** [btford/mary-poppins#62]
I got this error:

```
TypeError: Cannot read property 'title' of undefined
    at logTitle (/usr/local/lib/node_modules/mary-poppins/node_modules/metahub/metahub.js:416:83)
    at logDataSummary (/usr/local/lib/node_modules/mary-poppins/node_modules/metahub/metahub.js:408:10)
    at Poppins.Metahub.log (/usr/local/lib/node_modules/mary-poppins/node_modules/metahub/metahub.js:427:31)
    at Poppins.<anonymous> (/usr/local/lib/node_modules/mary-poppins/node_modules/metahub/metahub.js:297:10)
    at Poppins.Metahub._merge (/usr/local/lib/node_modules/mary-poppins/node_modules/metahub/metahub.js:309:22)
    at Function.EventEmitter.emit (events.js:95:17)
    at /usr/local/lib/node_modules/mary-poppins/node_modules/metahub/lib/server.js:13:12
    at callbacks (/usr/local/lib/node_modules/mary-poppins/node_modules/metahub/node_modules/express/lib/router/index.js:164:37)
    at param (/usr/local/lib/node_modules/mary-poppins/node_modules/metahub/node_modules/express/lib/router/index.js:138:11)
    at pass (/usr/local/lib/node_modules/mary-poppins/node_modules/metahub/node_modules/express/lib/router/index.js:145:5)
```

After a "close pull request" message. Here is the payload (from github):

``` json
{
  "action": "closed",
  "number": 1045,
  "pull_request": {
    "url": "https://api.github.com/repos/karma-runner/karma/pulls/1045",
    "id": 15132255,
    "html_url": "https://github.com/karma-runner/karma/pull/1045",
    "diff_url": "https://github.com/karma-runner/karma/pull/1045.diff",
    "patch_url": "https://github.com/karma-runner/karma/pull/1045.patch",
    "issue_url": "https://api.github.com/repos/karma-runner/karma/issues/1045",
    "number": 1045,
    "state": "closed",
    "title": "docs(troubleshooting): add the common ws issue",
    "user": {
      "login": "cironunes",
      "id": 469908,
      "avatar_url": "https://avatars.githubusercontent.com/u/469908?",
      "gravatar_id": "ac4189b770a4dbc0078935a68fff6f5c",
      "url": "https://api.github.com/users/cironunes",
      "html_url": "https://github.com/cironunes",
      "followers_url": "https://api.github.com/users/cironunes/followers",
      "following_url": "https://api.github.com/users/cironunes/following{/other_user}",
      "gists_url": "https://api.github.com/users/cironunes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cironunes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cironunes/subscriptions",
      "organizations_url": "https://api.github.com/users/cironunes/orgs",
      "repos_url": "https://api.github.com/users/cironunes/repos",
      "events_url": "https://api.github.com/users/cironunes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cironunes/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "",
    "created_at": "2014-04-24T17:44:42Z",
    "updated_at": "2014-07-26T00:10:24Z",
    "closed_at": "2014-07-26T00:10:24Z",
    "merged_at": "2014-07-26T00:10:24Z",
    "merge_commit_sha": "65935aff955893501a5942691996992bbb251e9e",
    "assignee": null,
    "milestone": null,
    "commits_url": "https://api.github.com/repos/karma-runner/karma/pulls/1045/commits",
    "review_comments_url": "https://api.github.com/repos/karma-runner/karma/pulls/1045/comments",
    "review_comment_url": "https://api.github.com/repos/karma-runner/karma/pulls/comments/{number}",
    "comments_url": "https://api.github.com/repos/karma-runner/karma/issues/1045/comments",
    "statuses_url": "https://api.github.com/repos/karma-runner/karma/statuses/7ee2f85eae4d89a08b74dce71bfebe3ff19e92f0",
    "head": {
      "label": "cironunes:troubleshooting/ws",
      "ref": "troubleshooting/ws",
      "sha": "7ee2f85eae4d89a08b74dce71bfebe3ff19e92f0",
      "user": {
        "login": "cironunes",
        "id": 469908,
        "avatar_url": "https://avatars.githubusercontent.com/u/469908?",
        "gravatar_id": "ac4189b770a4dbc0078935a68fff6f5c",
        "url": "https://api.github.com/users/cironunes",
        "html_url": "https://github.com/cironunes",
        "followers_url": "https://api.github.com/users/cironunes/followers",
        "following_url": "https://api.github.com/users/cironunes/following{/other_user}",
        "gists_url": "https://api.github.com/users/cironunes/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cironunes/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cironunes/subscriptions",
        "organizations_url": "https://api.github.com/users/cironunes/orgs",
        "repos_url": "https://api.github.com/users/cironunes/repos",
        "events_url": "https://api.github.com/users/cironunes/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cironunes/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 16144832,
        "name": "karma",
        "full_name": "cironunes/karma",
        "owner": {
          "login": "cironunes",
          "id": 469908,
          "avatar_url": "https://avatars.githubusercontent.com/u/469908?",
          "gravatar_id": "ac4189b770a4dbc0078935a68fff6f5c",
          "url": "https://api.github.com/users/cironunes",
          "html_url": "https://github.com/cironunes",
          "followers_url": "https://api.github.com/users/cironunes/followers",
          "following_url": "https://api.github.com/users/cironunes/following{/other_user}",
          "gists_url": "https://api.github.com/users/cironunes/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/cironunes/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/cironunes/subscriptions",
          "organizations_url": "https://api.github.com/users/cironunes/orgs",
          "repos_url": "https://api.github.com/users/cironunes/repos",
          "events_url": "https://api.github.com/users/cironunes/events{/privacy}",
          "received_events_url": "https://api.github.com/users/cironunes/received_events",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/cironunes/karma",
        "description": "Spectacular Test Runner for JavaScript",
        "fork": true,
        "url": "https://api.github.com/repos/cironunes/karma",
        "forks_url": "https://api.github.com/repos/cironunes/karma/forks",
        "keys_url": "https://api.github.com/repos/cironunes/karma/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/cironunes/karma/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/cironunes/karma/teams",
        "hooks_url": "https://api.github.com/repos/cironunes/karma/hooks",
        "issue_events_url": "https://api.github.com/repos/cironunes/karma/issues/events{/number}",
        "events_url": "https://api.github.com/repos/cironunes/karma/events",
        "assignees_url": "https://api.github.com/repos/cironunes/karma/assignees{/user}",
        "branches_url": "https://api.github.com/repos/cironunes/karma/branches{/branch}",
        "tags_url": "https://api.github.com/repos/cironunes/karma/tags",
        "blobs_url": "https://api.github.com/repos/cironunes/karma/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/cironunes/karma/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/cironunes/karma/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/cironunes/karma/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/cironunes/karma/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/cironunes/karma/languages",
        "stargazers_url": "https://api.github.com/repos/cironunes/karma/stargazers",
        "contributors_url": "https://api.github.com/repos/cironunes/karma/contributors",
        "subscribers_url": "https://api.github.com/repos/cironunes/karma/subscribers",
        "subscription_url": "https://api.github.com/repos/cironunes/karma/subscription",
        "commits_url": "https://api.github.com/repos/cironunes/karma/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/cironunes/karma/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/cironunes/karma/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/cironunes/karma/issues/comments/{number}",
        "contents_url": "https://api.github.com/repos/cironunes/karma/contents/{+path}",
        "compare_url": "https://api.github.com/repos/cironunes/karma/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/cironunes/karma/merges",
        "archive_url": "https://api.github.com/repos/cironunes/karma/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/cironunes/karma/downloads",
        "issues_url": "https://api.github.com/repos/cironunes/karma/issues{/number}",
        "pulls_url": "https://api.github.com/repos/cironunes/karma/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/cironunes/karma/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/cironunes/karma/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/cironunes/karma/labels{/name}",
        "releases_url": "https://api.github.com/repos/cironunes/karma/releases{/id}",
        "created_at": "2014-01-22T16:28:43Z",
        "updated_at": "2014-06-24T11:43:34Z",
        "pushed_at": "2014-06-24T11:43:34Z",
        "git_url": "git://github.com/cironunes/karma.git",
        "ssh_url": "git@github.com:cironunes/karma.git",
        "clone_url": "https://github.com/cironunes/karma.git",
        "svn_url": "https://github.com/cironunes/karma",
        "homepage": "http://karma-runner.github.io",
        "size": 6522,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "CoffeeScript",
        "has_issues": false,
        "has_downloads": true,
        "has_wiki": false,
        "forks_count": 1,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 1,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
      }
    },
    "base": {
      "label": "karma-runner:master",
      "ref": "master",
      "sha": "3873c5311932176a08e774f3efe1c21ee74064c0",
      "user": {
        "login": "karma-runner",
        "id": 3284117,
        "avatar_url": "https://avatars.githubusercontent.com/u/3284117?",
        "gravatar_id": "847cab27bf461c01b135512af49191d6",
        "url": "https://api.github.com/users/karma-runner",
        "html_url": "https://github.com/karma-runner",
        "followers_url": "https://api.github.com/users/karma-runner/followers",
        "following_url": "https://api.github.com/users/karma-runner/following{/other_user}",
        "gists_url": "https://api.github.com/users/karma-runner/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/karma-runner/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/karma-runner/subscriptions",
        "organizations_url": "https://api.github.com/users/karma-runner/orgs",
        "repos_url": "https://api.github.com/users/karma-runner/repos",
        "events_url": "https://api.github.com/users/karma-runner/events{/privacy}",
        "received_events_url": "https://api.github.com/users/karma-runner/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 2560988,
        "name": "karma",
        "full_name": "karma-runner/karma",
        "owner": {
          "login": "karma-runner",
          "id": 3284117,
          "avatar_url": "https://avatars.githubusercontent.com/u/3284117?",
          "gravatar_id": "847cab27bf461c01b135512af49191d6",
          "url": "https://api.github.com/users/karma-runner",
          "html_url": "https://github.com/karma-runner",
          "followers_url": "https://api.github.com/users/karma-runner/followers",
          "following_url": "https://api.github.com/users/karma-runner/following{/other_user}",
          "gists_url": "https://api.github.com/users/karma-runner/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/karma-runner/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/karma-runner/subscriptions",
          "organizations_url": "https://api.github.com/users/karma-runner/orgs",
          "repos_url": "https://api.github.com/users/karma-runner/repos",
          "events_url": "https://api.github.com/users/karma-runner/events{/privacy}",
          "received_events_url": "https://api.github.com/users/karma-runner/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/karma-runner/karma",
        "description": "Spectacular Test Runner for JavaScript",
        "fork": false,
        "url": "https://api.github.com/repos/karma-runner/karma",
        "forks_url": "https://api.github.com/repos/karma-runner/karma/forks",
        "keys_url": "https://api.github.com/repos/karma-runner/karma/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/karma-runner/karma/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/karma-runner/karma/teams",
        "hooks_url": "https://api.github.com/repos/karma-runner/karma/hooks",
        "issue_events_url": "https://api.github.com/repos/karma-runner/karma/issues/events{/number}",
        "events_url": "https://api.github.com/repos/karma-runner/karma/events",
        "assignees_url": "https://api.github.com/repos/karma-runner/karma/assignees{/user}",
        "branches_url": "https://api.github.com/repos/karma-runner/karma/branches{/branch}",
        "tags_url": "https://api.github.com/repos/karma-runner/karma/tags",
        "blobs_url": "https://api.github.com/repos/karma-runner/karma/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/karma-runner/karma/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/karma-runner/karma/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/karma-runner/karma/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/karma-runner/karma/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/karma-runner/karma/languages",
        "stargazers_url": "https://api.github.com/repos/karma-runner/karma/stargazers",
        "contributors_url": "https://api.github.com/repos/karma-runner/karma/contributors",
        "subscribers_url": "https://api.github.com/repos/karma-runner/karma/subscribers",
        "subscription_url": "https://api.github.com/repos/karma-runner/karma/subscription",
        "commits_url": "https://api.github.com/repos/karma-runner/karma/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/karma-runner/karma/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/karma-runner/karma/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/karma-runner/karma/issues/comments/{number}",
        "contents_url": "https://api.github.com/repos/karma-runner/karma/contents/{+path}",
        "compare_url": "https://api.github.com/repos/karma-runner/karma/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/karma-runner/karma/merges",
        "archive_url": "https://api.github.com/repos/karma-runner/karma/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/karma-runner/karma/downloads",
        "issues_url": "https://api.github.com/repos/karma-runner/karma/issues{/number}",
        "pulls_url": "https://api.github.com/repos/karma-runner/karma/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/karma-runner/karma/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/karma-runner/karma/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/karma-runner/karma/labels{/name}",
        "releases_url": "https://api.github.com/repos/karma-runner/karma/releases{/id}",
        "created_at": "2011-10-12T07:55:46Z",
        "updated_at": "2014-07-25T21:48:53Z",
        "pushed_at": "2014-07-26T00:10:23Z",
        "git_url": "git://github.com/karma-runner/karma.git",
        "ssh_url": "git@github.com:karma-runner/karma.git",
        "clone_url": "https://github.com/karma-runner/karma.git",
        "svn_url": "https://github.com/karma-runner/karma",
        "homepage": "http://karma-runner.github.io",
        "size": 16120,
        "stargazers_count": 3806,
        "watchers_count": 3806,
        "language": "CoffeeScript",
        "has_issues": true,
        "has_downloads": true,
        "has_wiki": false,
        "forks_count": 646,
        "mirror_url": null,
        "open_issues_count": 203,
        "forks": 646,
        "open_issues": 203,
        "watchers": 3806,
        "default_branch": "master"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/karma-runner/karma/pulls/1045"
      },
      "html": {
        "href": "https://github.com/karma-runner/karma/pull/1045"
      },
      "issue": {
        "href": "https://api.github.com/repos/karma-runner/karma/issues/1045"
      },
      "comments": {
        "href": "https://api.github.com/repos/karma-runner/karma/issues/1045/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/karma-runner/karma/pulls/1045/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/karma-runner/karma/pulls/comments/{number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/karma-runner/karma/pulls/1045/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/karma-runner/karma/statuses/7ee2f85eae4d89a08b74dce71bfebe3ff19e92f0"
      }
    },
    "merged": true,
    "mergeable": null,
    "mergeable_state": "unknown",
    "merged_by": {
      "login": "vojtajina",
      "id": 46647,
      "avatar_url": "https://avatars.githubusercontent.com/u/46647?",
      "gravatar_id": "d59bdceef864e67df13167d806d6da63",
      "url": "https://api.github.com/users/vojtajina",
      "html_url": "https://github.com/vojtajina",
      "followers_url": "https://api.github.com/users/vojtajina/followers",
      "following_url": "https://api.github.com/users/vojtajina/following{/other_user}",
      "gists_url": "https://api.github.com/users/vojtajina/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vojtajina/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vojtajina/subscriptions",
      "organizations_url": "https://api.github.com/users/vojtajina/orgs",
      "repos_url": "https://api.github.com/users/vojtajina/repos",
      "events_url": "https://api.github.com/users/vojtajina/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vojtajina/received_events",
      "type": "User",
      "site_admin": false
    },
    "comments": 5,
    "review_comments": 5,
    "commits": 1,
    "additions": 12,
    "deletions": 0,
    "changed_files": 1
  },
  "repository": {
    "id": 2560988,
    "name": "karma",
    "full_name": "karma-runner/karma",
    "owner": {
      "login": "karma-runner",
      "id": 3284117,
      "avatar_url": "https://avatars.githubusercontent.com/u/3284117?",
      "gravatar_id": "847cab27bf461c01b135512af49191d6",
      "url": "https://api.github.com/users/karma-runner",
      "html_url": "https://github.com/karma-runner",
      "followers_url": "https://api.github.com/users/karma-runner/followers",
      "following_url": "https://api.github.com/users/karma-runner/following{/other_user}",
      "gists_url": "https://api.github.com/users/karma-runner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/karma-runner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/karma-runner/subscriptions",
      "organizations_url": "https://api.github.com/users/karma-runner/orgs",
      "repos_url": "https://api.github.com/users/karma-runner/repos",
      "events_url": "https://api.github.com/users/karma-runner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/karma-runner/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/karma-runner/karma",
    "description": "Spectacular Test Runner for JavaScript",
    "fork": false,
    "url": "https://api.github.com/repos/karma-runner/karma",
    "forks_url": "https://api.github.com/repos/karma-runner/karma/forks",
    "keys_url": "https://api.github.com/repos/karma-runner/karma/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/karma-runner/karma/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/karma-runner/karma/teams",
    "hooks_url": "https://api.github.com/repos/karma-runner/karma/hooks",
    "issue_events_url": "https://api.github.com/repos/karma-runner/karma/issues/events{/number}",
    "events_url": "https://api.github.com/repos/karma-runner/karma/events",
    "assignees_url": "https://api.github.com/repos/karma-runner/karma/assignees{/user}",
    "branches_url": "https://api.github.com/repos/karma-runner/karma/branches{/branch}",
    "tags_url": "https://api.github.com/repos/karma-runner/karma/tags",
    "blobs_url": "https://api.github.com/repos/karma-runner/karma/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/karma-runner/karma/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/karma-runner/karma/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/karma-runner/karma/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/karma-runner/karma/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/karma-runner/karma/languages",
    "stargazers_url": "https://api.github.com/repos/karma-runner/karma/stargazers",
    "contributors_url": "https://api.github.com/repos/karma-runner/karma/contributors",
    "subscribers_url": "https://api.github.com/repos/karma-runner/karma/subscribers",
    "subscription_url": "https://api.github.com/repos/karma-runner/karma/subscription",
    "commits_url": "https://api.github.com/repos/karma-runner/karma/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/karma-runner/karma/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/karma-runner/karma/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/karma-runner/karma/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/karma-runner/karma/contents/{+path}",
    "compare_url": "https://api.github.com/repos/karma-runner/karma/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/karma-runner/karma/merges",
    "archive_url": "https://api.github.com/repos/karma-runner/karma/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/karma-runner/karma/downloads",
    "issues_url": "https://api.github.com/repos/karma-runner/karma/issues{/number}",
    "pulls_url": "https://api.github.com/repos/karma-runner/karma/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/karma-runner/karma/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/karma-runner/karma/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/karma-runner/karma/labels{/name}",
    "releases_url": "https://api.github.com/repos/karma-runner/karma/releases{/id}",
    "created_at": "2011-10-12T07:55:46Z",
    "updated_at": "2014-07-25T21:48:53Z",
    "pushed_at": "2014-07-26T00:10:25Z",
    "git_url": "git://github.com/karma-runner/karma.git",
    "ssh_url": "git@github.com:karma-runner/karma.git",
    "clone_url": "https://github.com/karma-runner/karma.git",
    "svn_url": "https://github.com/karma-runner/karma",
    "homepage": "http://karma-runner.github.io",
    "size": 16120,
    "stargazers_count": 3806,
    "watchers_count": 3806,
    "language": "CoffeeScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": false,
    "forks_count": 646,
    "mirror_url": null,
    "open_issues_count": 203,
    "forks": 646,
    "open_issues": 203,
    "watchers": 3806,
    "default_branch": "master"
  },
  "sender": {
    "login": "vojtajina",
    "id": 46647,
    "avatar_url": "https://avatars.githubusercontent.com/u/46647?",
    "gravatar_id": "d59bdceef864e67df13167d806d6da63",
    "url": "https://api.github.com/users/vojtajina",
    "html_url": "https://github.com/vojtajina",
    "followers_url": "https://api.github.com/users/vojtajina/followers",
    "following_url": "https://api.github.com/users/vojtajina/following{/other_user}",
    "gists_url": "https://api.github.com/users/vojtajina/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/vojtajina/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/vojtajina/subscriptions",
    "organizations_url": "https://api.github.com/users/vojtajina/orgs",
    "repos_url": "https://api.github.com/users/vojtajina/repos",
    "events_url": "https://api.github.com/users/vojtajina/events{/privacy}",
    "received_events_url": "https://api.github.com/users/vojtajina/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

**Comment by vojtajina** [comment]
For some reason, github sets "pull_request" instead of "issue" (which it does for comments on prs).

**Comment by btford** [comment]
Fixed in https://github.com/btford/metahub/commit/bd8c4bf198a644d66fb66cb9b41e2cb41ddcdd4b

I'll release a complementary update to mary-poppins shortly.

**Comment by vojtajina** [comment]
You are fast.
